language: python

services:
  - docker

env:
  - GUAC_ARG='-f docker-compose.yml -f docker-compose.guac.yml' ATMO_TEST_ARG='-f docker-compose.atmo-test.yml' TROPO_TEST_ARG='-f docker-compose.tropo-test.yml'

before_install:
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - docker-compose pull
  - docker-compose ${ATMO_TEST_ARG} pull
  - docker-compose ${TROPO_TEST_ARG} pull

script:
  - docker-compose config
  - docker-compose ${GUAC_ARG} config
  - docker-compose ${ATMO_TEST_ARG} config
  - docker-compose ${TROPO_TEST_ARG} config
  - docker-compose build
  - docker-compose ${ATMO_TEST_ARG} up --exit-code-from atmosphere
  - docker-compose ${TROPO_TEST_ARG} up --exit-code-from troposphere
