---
version: '3'

services:

  redis:
    image: 'redis:latest'

  celery:
    build: './celery'
    volumes:
      - 'atmo:/opt/dev/atmosphere'
      - 'atmo-ansible:/opt/dev/atmosphere-ansible'
    depends_on:
      - 'redis'
    extra_hosts:
      - 'postgres:${dockerhost}'

  atmosphere:
    image: 'cyverse/atmosphere:latest'
    volumes:
      - 'atmo:/opt/dev/atmosphere'
      - 'atmo-ansible:/opt/dev/atmosphere-ansible'
      - '../atmosphere-docker-secrets:/opt/dev/atmosphere-docker-secrets'
      - '/boot:/boot'
      - '/lib/modules:/lib/modules'
    extra_hosts:
      - 'postgres:${dockerhost}'

  troposphere:
    image: 'cyverse/troposphere:latest'
    volumes:
      - '../atmosphere-docker-secrets:/opt/dev/atmosphere-docker-secrets'
    depends_on:
      - 'atmosphere'
    ports:
      - '443:443'
      - '80:80'
    extra_hosts:
      - 'postgres:${dockerhost}'

volumes:
  atmo:
  atmo-ansible:
