---

version: '3'

services:

  postgres:
    image: 'postgres:9.6'
    environment:
      POSTGRES_USER: 'atmosphere_db_user'
      POSTGRES_PASSWORD: 'atmosphere_db_pass'
      POSTGRES_DB: 'atmosphere_db'

  sut:
    build: .
    entrypoint: '. /opt/env/atmo/bin/activate && /root/test.sh'
    depends_on:
      - 'postgres'
